### ISSUE TITLE
还是github看着舒服，gitee就是一埋屎

### ISSUE THREAD

**Issue by sonwa** [Ikaros-521/boa_cgi_SMS#1]
还是github看着舒服，gitee就是一埋屎。更新代码还是用github吧

**Comment by Ikaros-521** [comment]
www，我都是传github同步gitee的，国内还是不少人访问github很慢（没加速）

**Comment by sonwa** [comment]
的确是有时会慢，不过还是用github。基本上在gitee上的都会在github搜一下，有就用github。gitee限制太多

**Comment by Ikaros-521** [comment]
> 

是的
