### ISSUE TITLE
大佬能发份HLX-SMS学习学习吗？

### ISSUE THREAD

**Issue by sonwa** [Ikaros-521/boa_cgi_SMS#2]
大佬能发份HLX-SMS学习学习吗？

**Comment by Ikaros-521** [comment]
这个仓库就是里面整理出来的版本了

**Comment by sonwa** [comment]
看见说正式点？

<img width="969" alt="image" src="https://user-images.githubusercontent.com/1425134/174571737-5ccfb84e-2a92-4d8d-99c0-890c18603166.png">

**Comment by Ikaros-521** [comment]
> 看见说正式点？
> 
> <img alt="image" width="969" src="https://user-images.githubusercontent.com/1425134/174571737-5ccfb84e-2a92-4d8d-99c0-890c18603166.png">

就是这个 改了个名字 优化了一下

**Comment by sonwa** [comment]
<img width="123" alt="image" src="https://user-images.githubusercontent.com/1425134/174694482-86cf7b7f-fe95-4a19-9400-acb3a43707e0.png">

**Comment by Ikaros-521** [comment]
![_WXR(K%FM@UEM 2XF3NS5LN](https://user-images.githubusercontent.com/40910637/174726022-6ca13f01-15fa-4da4-ab5c-ab3283bb54fb.jpg)

**Comment by Ikaros-521** [comment]
![image](https://user-images.githubusercontent.com/40910637/174726112-468a1fc0-5c85-4d19-bff9-b3eaaf7a0224.png)
